# Generated by Django 3.2.9 on 2021-11-02 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_original', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'verbose_name': '作品',
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('text', models.CharField(max_length=255)),
                ('character', models.CharField(blank=True, max_length=255, null=True)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='birthday.media')),
            ],
            options={
                'verbose_name': '更新紀錄',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_original', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday_date', models.DateField(blank=True, null=True)),
                ('birthday_note', models.CharField(blank=True, max_length=128, null=True)),
                ('gender', models.CharField(blank=True, max_length=128, null=True)),
                ('url', models.CharField(blank=True, max_length=512, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birthday.media')),
            ],
            options={
                'verbose_name': '角色',
            },
        ),
    ]
